### ISSUE TITLE
404 Page on Javascript Link

### ISSUE THREAD

**Issue by 0xIO32** [Satistile/webframetwo#1]
The Javascript Link referenced in the Readme "https://satistile.github.io/webframeone/resources/webframetwo.js" does return a 404 error.
![20240223_12h16m23s_grim](https://github.com/Satistile/webframetwo/assets/77546847/b7e7442f-c726-404f-b9c2-8a1bc50c4d19)

**Comment by Satistile** [comment]
This happened due to an error in the readme.md. The error is corrected now.
For using the webframetwo JavaScript file, use https://satistile.github.io/webframetwo/resources/webframetwo.js
